### ISSUE TITLE
Intermittent DNS issues disable the controller

### ISSUE THREAD

**Issue by gabrtv** [Azure/aci-connector-k8s#1]
After running for 3 hours, the controller was disabled and not processing pod deletions.  Logs showed the following stacktrace:

```
{ Error: getaddrinfo EAI_AGAIN management.azure.com:443
    at Object.exports._errnoException (util.js:1016:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'management.azure.com',
  host: 'management.azure.com',
  port: 443 }
sending update.
sending update.
sending update.
```

**Comment by lachie83** [comment]
Fixed in #22
