### ISSUE TITLE
Error from server: no preferred addresses found; known addresses: []

### ISSUE THREAD

**Issue by robotica72** [Azure/aci-connector-k8s#12]
So no issues getting the Pod up, its healthy - but the nginx deployment will not start and has a single log entry : Error from server: no preferred addresses found; known addresses: []

If it helps, internally Im running Calico in Routed mode.

Azure RG Shows:

Operation name
Write ContainerGroups
Time stamp
Wed Jul 26 2017 19:46:53 GMT-0400 (Eastern Daylight Time)
Event initiated by
azure-cli-2017-07-26-22-52-52
Error code
InvalidResourceNamespace
Message
The resource namespace 'Microsoft.Container' is invalid.

**Comment by junaid18183** [comment]
Facing the same issue

**Comment by yaron2** [comment]
Having the same issue.

aci-connector pod logs show this:

2017-07-27T10:59:50.843627549Z container scheduler
2017-07-27T10:59:50.963454804Z { Error: The resource namespace 'Microsoft.Container' is invalid.
2017-07-27T10:59:50.963828817Z     at client.pipeline (/app/node_modules/azure-arm-resource/lib/resource/operations/resources.js:1768:19)
2017-07-27T10:59:50.963835717Z     at retryCallback (/app/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
2017-07-27T10:59:50.963838717Z     at retryCallback (/app/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
2017-07-27T10:59:50.963842117Z     at handleRedirect (/app/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
2017-07-27T10:59:50.963844917Z     at /app/node_modules/ms-rest-azure/lib/filters/rpRegistrationFilter.js:59:14
2017-07-27T10:59:50.963847717Z     at Request.defaultRequest [as _callback] (/app/node_modules/ms-rest/lib/requestPipeline.js:125:16)
2017-07-27T10:59:50.963855818Z     at Request.self.callback (/app/node_modules/request/request.js:188:22)
2017-07-27T10:59:50.963859418Z     at emitTwo (events.js:125:13)
2017-07-27T10:59:50.963862118Z     at Request.emit (events.js:213:7)
2017-07-27T10:59:50.963864818Z     at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
2017-07-27T10:59:50.963868218Z     at emitOne (events.js:120:20)
2017-07-27T10:59:50.963870818Z     at Request.emit (events.js:210:7)
2017-07-27T10:59:50.963873518Z     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
2017-07-27T10:59:50.963876418Z     at Object.onceWrapper (events.js:314:30)
2017-07-27T10:59:50.963879018Z     at emitNone (events.js:110:20)
2017-07-27T10:59:50.963881518Z     at IncomingMessage.emit (events.js:207:7)
2017-07-27T10:59:50.963884119Z   statusCode: 404,
2017-07-27T10:59:50.963886719Z   request: 
2017-07-27T10:59:50.963889219Z    { rawResponse: false,
2017-07-27T10:59:50.963891719Z      queryString: {},
2017-07-27T10:59:50.963894719Z      url: 'https://management.azure.com/subscriptions/da6d8e3f-688a-4d75-a5f0-412b7a223422/resourcegroups/yaronk8sacii-rg/providers/Microsoft.Container//containerGroups/nginx?api-version=2017-04-01-preview',
2017-07-27T10:59:50.963897919Z      method: 'PUT',
2017-07-27T10:59:50.963900419Z      headers: 
2017-07-27T10:59:50.963902919Z       { 'x-ms-client-request-id': '003fb11a-7f84-48a8-a770-a9e7735c42d3',
2017-07-27T10:59:50.963905519Z         'accept-language': 'en-US',
2017-07-27T10:59:50.963908219Z         'Content-Type': 'application/json; charset=utf-8',
2017-07-27T10:59:50.963911619Z         'user-agent': 'Node/v8.1.2 (x64-Linux-4.4.0-87-generic) ms-rest/2.2.1 ms-rest-azure/2.2.3 azure-arm-resource/2.0.0-preview Azure-SDK-For-Node' },
2017-07-27T10:59:50.96391532Z      body: '{"location":"westus","tags":{"orchestrator":"kubernetes"},"properties":{"osType":"linux","containers":[{"name":"nginx","properties":{"ports":[{"port":80}],"image":"nginx"}}],"ipAddress":{"type":"Public","ports":[{"protocol":"TCP","port":80}]}}}' },
2017-07-27T10:59:50.96392102Z   response: 
2017-07-27T10:59:50.96392962Z    { body: '{"error":{"code":"InvalidResourceNamespace","message":"The resource namespace \'Microsoft.Container\' is invalid."}}',

**Comment by yaron2** [comment]
This seems related to PR #9 

As a temp workaround you can edit aci-connector.yaml and replace the image with shibayan/aci-connector-k8s which has the correct resource configs.

**Comment by robotica72** [comment]
@yaron2 Thats awesome, I didnt look at the PR's last night, probably should have...  Thanks for the find, going to fix that now.

**Comment by alancnet** [comment]
@yaron even with `shibayan/aci-connector-k8s`, I'm still getting `Error from server: no preferred addresses found; known addresses: []`. Any idea?

**Comment by yaron2** [comment]
What do the logs of the aci connector show?

**Comment by alancnet** [comment]
@yaron2 
```
k8s pod creater/updater
nginx
sending update.
container deleter
container scheduler
container deleter
container deleter
k8s pod creater/updater
sending update.
container deleter
nginx
container deleter
container scheduler
container deleter
container deleter
sending update.
k8s pod creater/updater
nginx
container deleter
container scheduler
container deleter
sending update.
k8s pod creater/updater
nginx
container deleter
container scheduler
container deleter
```
and it goes on like this.

**Comment by yaron2** [comment]
Working for me..

Please try the following:
kubectl delete pod aci-connector

watch 'kubectl get nodes'

Wait until you no longer see the aci-connector in the list of nodes.
Then do kubectl create -f /examples/aci-connector.yaml

Wait until you see aci-connector with kubectl get nodes
Then do kubectl create -f examples/nginx-pod.yaml

**Comment by alancnet** [comment]
Not working for me:

```bash
alco@alco-cloud:~$ kubectl delete pod aci-connector
pod "aci-connector" deleted
alco@alco-cloud:~$ kubectl get nodes
NAME                    STATUS                     AGE       VERSION
aci-connector           Ready                      2m        1.6.6
k8s-agent-9f6c8a24-0    Ready                      15d       v1.6.6
k8s-master-9f6c8a24-0   Ready,SchedulingDisabled   15d       v1.6.6
alco@alco-cloud:~$ kubectl get nodes
NAME                    STATUS                     AGE       VERSION
k8s-agent-9f6c8a24-0    Ready                      15d       v1.6.6
k8s-master-9f6c8a24-0   Ready,SchedulingDisabled   15d       v1.6.6
alco@alco-cloud:~$ kubectl create -f git/qsa-pipeline/docker/config/pods/aci-connector.yaml 
pod "aci-connector" created
alco@alco-cloud:~$ kubectl get nodes
NAME                    STATUS                     AGE       VERSION
aci-connector           Ready                      8s        1.6.6
k8s-agent-9f6c8a24-0    Ready                      15d       v1.6.6
k8s-master-9f6c8a24-0   Ready,SchedulingDisabled   15d       v1.6.6
alco@alco-cloud:~$ kubectl create -f git/qsa-pipeline/docker/config/pods/nginx-pod.yaml 
pod "nginx" created
alco@alco-cloud:~$ kubectl logs -f nginx
Error from server: no preferred addresses found; known addresses: []
alco@alco-cloud:~$ 
```

**Comment by yaron2** [comment]
Can you share the YAMLs for aci-connector and nginx-pod?

**Comment by alancnet** [comment]
@yaron2 see above. I had appended to my comment

**Comment by yaron2** [comment]
Weird.. :\

Perhaps it's a regional availability issue? I have my aci and acs resource groups on eastus..
That's basically the only difference I see between your env and mine (unless you run in eastus also).

**Comment by alancnet** [comment]
Naw.. Westus.. But I am seeing other strange issues.. Periodically I see ghosts of old containers pop up. Perhaps I'll clear out the resource group and try again... on the faith that if I do exactly what you're doing, it will work :) .. Thanks!

**Comment by yaron2** [comment]
I edited my comment above regarding Calico.

I was able to spot ghost pods as well.
I believe the "under the hood" kubelet may not get a chance to clear pods so when it gets registered again it still has the pods.

**Comment by junaid18183** [comment]
Thanks @yaron2  I confirm its working with your docker image.

Also I think the example needs a small tweak , rather than using Pod for aci-connector we should use deployment so that the aci-connector is always running. I will do a quick PR if needed.

**Comment by yaron2** [comment]
I agree.
Best to open a seperate issue for this.

**Comment by junaid18183** [comment]
created a PR - https://github.com/Azure/aci-connector-k8s/pull/15

**Comment by robotica72** [comment]
Im running Calico and I don't see the issue - but I am running Calico in routed mode and not overlay - that may be the difference for me.  I also had an odd error when passing :latest for the container image (Dont recall now) but I just pull the container now without the :latest and had no issues.

**Comment by jinmiaoms** [comment]
I'm seeing the exact same issue as @alancnet reported.  I did a describe on the aci-connector node, and saw the following under Conditions:
 NetworkUnavailable    True    Wed, 16 Aug 2017 00:00:42 +0800         Wed, 16 Aug 2017 00:00:42 +0800   NoRouteCreated                  RouteController failed to create a route

And Addresses is empty.  The agent node doesn't have this problem.  Is this causing this error?  I tried both eastus and westus.

**Comment by loekd** [comment]
+1 on the issue in WestEurope, using the approach from the readme.md.

**Comment by shanepeckham** [comment]
I see the same as @jinmiaoms, the aci-connector pod status is:
NetworkUnavailable
True
0 seconds
0 seconds
NoRouteCreated
RouteController failed to create a route

And then you get the no know addresses issue. I get this with both the microsoft/aci-connector-k8s:latest image and the shibayan/aci-connector-k8s:latest image. My deployment is in WestEurope.

**Comment by rbitia** [comment]
I've recreated the issue with 'kubectl ngnix logs' returning no known addresses. Thanks for all the input! Working on getting a fix.

**Comment by lachie83** [comment]
loekd @jinmiaoms Can you kindly confirm that the provider is registered under the subscription that the SP was created?

Details here -- https://github.com/Azure/aci-connector-k8s#confirm-microsoftcontainerinstance-provider-is-registered

**Comment by lachie83** [comment]
Oh! Not I have a better grasp on what's happening here. Please disregard my previous comment. Both `kubectl exec` and `kubectl logs` are not currently implemented via the connector. Going to document in #46

**Comment by lachie83** [comment]
You can use the `az container logs` command in the Azure CLI to pull the logs from the container group currently.

**Comment by lachie83** [comment]
Closing as I don't believe there is any further follow up. Please reopen if that's not the case @robotica72
