### ISSUE TITLE
The resource namespace 'Microsoft.Container' is invalid.

### ISSUE THREAD

**Issue by alancnet** [Azure/aci-connector-k8s#13]
I am using aci-connector-k8s with Kubernetes on ACS.

I am attempting to deploy the [sample nginx yaml](https://github.com/Azure/aci-connector-k8s/blob/master/examples/nginx-pod.yaml), and the aci-connector logs show this:

```
{ Error: The resource namespace 'Microsoft.Container' is invalid.
    at client.pipeline (/app/node_modules/azure-arm-resource/lib/resource/operations/resources.js:1768:19)
    at retryCallback (/app/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (/app/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/app/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
    at /app/node_modules/ms-rest-azure/lib/filters/rpRegistrationFilter.js:59:14
    at Request.defaultRequest [as _callback] (/app/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
  statusCode: 404,
  request: 
   { rawResponse: false,
     queryString: {},
     url: 'https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/USWRDACI/providers/Microsoft.Container//containerGroups/nginx?api-version=2017-04-01-preview',
     method: 'PUT',
     headers: 
      { 'x-ms-client-request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        'accept-language': 'en-US',
        'Content-Type': 'application/json; charset=utf-8',
        'user-agent': 'Node/v8.1.2 (x64-Linux-4.4.0-83-generic) ms-rest/2.2.1 ms-rest-azure/2.2.3 azure-arm-resource/2.0.0-preview Azure-SDK-For-Node' },
     body: '{"location":"westus","tags":{"orchestrator":"kubernetes"},"properties":{"osType":"linux","containers":[{"name":"nginx","properties":{"ports":[{"port":80}],"image":"nginx"}}],"ipAddress":{"type":"Public","ports":[{"protocol":"TCP","port":80}]}}}' },
  response: 
   { body: '{"error":{"code":"InvalidResourceNamespace","message":"The resource namespace \'Microsoft.Container\' is invalid."}}',
     headers: 
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-failure-cause': 'gateway',
        'x-ms-request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        'x-ms-correlation-request-id': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        'x-ms-routing-request-id': 'WESTUS:20170727T205907Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Thu, 27 Jul 2017 20:59:06 GMT',
        connection: 'close',
        'content-length': '114' },
     statusCode: 404 },
  code: 'InvalidResourceNamespace',
  body: 
   { code: 'InvalidResourceNamespace',
     message: 'The resource namespace \'Microsoft.Container\' is invalid.' } }
```

**Comment by alancnet** [comment]
It looks like it could be the wrong namespace. Should it be `Microsoft.ContainerInstance`?

![image](https://user-images.githubusercontent.com/2042102/28692464-826cab7a-72d5-11e7-9289-9c8082b6cc24.png)

**Comment by wbuchwalter** [comment]
See https://github.com/Azure/aci-connector-k8s/pull/9, where this was just fixed.

**Comment by alancnet** [comment]
@wbuchwalter Awesome! thanks!
